# Generated by Django 4.1.3 on 2022-11-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_content_upload_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='', upload_to='static/thumbnail/'),
        ),
    ]
